### PR TITLE
Adding notebook showing derivatives of ID-VG

### PR DESCRIPTION
**Pull request by bmurmann**
Adding notebook showing derivatives of ID-VG.

### CODE REVIEW

**Comment by QuantamHD** [comment]
Very cool @bmurmann!

I feel like notebooks are an excellent vehicle to do real science. The PR model seems really cool for this kind of analysis

**Comment by proppy** [comment]
Should we merge the two notebook together?
https://github.com/google/skywater-pdk-sky130-raw-data/blob/main/notebooks/sky130-raw-data-viz.ipynb

**Comment by bmurmann** [comment]
I'd leave them separate, because the derivatives analysis is somewhat specific to analog design, whereas yours is more generic. I think there can be many more of these notebooks for special purposes/interests. E.g. I am working on something for output conductance (intrinsic gain).

Really up to you, though.

**Comment by proppy** [comment]
@bmurmann let me rename mine them, so that the name is inline with yours and a little bit more explicit about what it is doing (`sky130_plot_currents`?).

**Comment by bmurmann** [comment]
Sounds good.

**Pull request merged**
